# Generated by Django 3.2.9 on 2022-02-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('realname', models.CharField(max_length=40)),
                ('emailid', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
    ]
