# Generated by Django 3.2.9 on 2022-02-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygallery', '0003_remove_gallery_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='user',
            field=models.CharField(default='admin', max_length=40),
        ),
    ]
