# Generated by Django 3.2.9 on 2022-02-24 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygallery', '0004_gallery_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
