# Generated by Django 3.2.9 on 2022-02-24 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygallery', '0005_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='cat',
        ),
    ]
