# Generated by Django 3.2.9 on 2022-02-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygallery', '0006_rename_category_category_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.CharField(default='admin', max_length=40),
        ),
    ]
